const portfolioDataRaw = {
  "profile": {
    "name": "Prof. Dr. Halit YANIKKAYA",
    "title": "İktisat",
    "email": "halityanikkaya@gtu.edu.tr",
    "phone": "(262) 605 14 20/14 32",
    "office": "İşletme Binası, 137",
    "web": "https://sites.google.com/view/halityanikkaya",
    "research_areas": [
      "İktisadi Büyüme",
      "Kalkınma Ekonomisi",
      "Kurumsal İktisat",
      "Uluslararası Ticaret"
    ],
    "education": [
      {
        "degree": "Doktora",
        "university": "University of Delaware",
        "field": "İktisat",
        "year": "2001"
      },
      {
        "degree": "Yüksek lisans",
        "university": "University of Delaware",
        "field": "İktisat",
        "year": "1997"
      },
      {
        "degree": "Lisans",
        "university": "Gazi Üniversitesi",
        "field": "İktisat",
        "year": "1993"
      }
    ]
  },
  "publications": [
    {
      "category": "Yayımlanmış Makaleler",
      "items": [
        "“How Profitability Differs between Conventional and Islamic Banks: A Dynamic Panel Data Approach” (N. Gümüş ve U. Y. Pabuçcu ile), Pacific-Basin Finance Journal, 2018(48), 99-111.",
        "“The Past and the Future Trade Patterns of the MENA Region: The Pursuit of Growth*” (A. Altun ve P. Tat ile), The Journal of World Economy, 2026, 73, 81-109.",
        "“Does Global Value Chain Participation Lead to Economic Upgrading?*” (H. A. Özer ve T. Turan ile), European Journal of Development Research, 2026, basım aşamasında.",
        "“Does Participating in Agricultural Global Value Chains Promote Agricultural Growth?*” (H. A. Özer ve T. Turan ile), Agribusiness, 2026, basım aşamasında.",
        "“Does Participation in Agricultural GVCs Impede Manufacturing Growth?*” (H. A. Özer ve T. Turan ile), Agricultural Economics, 2026, 72(5), 292-301.",
        "“Does Participation in Energy GVCs Promote Value-Added Growth?*” (T. Turan ve H. A. Özer ile), Applied Economic Letters, 2026, basım aşamasında.",
        "“The Impact of Participation in Global Value Chains on the Globalization of Innovation Systems*” (H. Karaboğa ve A. Altun ile), Applied Economic Letters, 2026, 33(7), 923-927.",
        "“Are Tariffs Always Bad for Growth? Evidence from Cross-Sectoral Analysis*” (A. Altun ve P. Tat ile), Economic Change and Restructuring, 2026, 59(1), 1-19.",
        "“The Impact of Rule of Law on Social Capital: Transplant Effect versus Legal Family*” (G. Sağlam ile), Acta Oeconomica, 2025, 75(3), 353-372.",
        "“Assessing the Impact of Road Infrastructure on Air Pollution: Evidence from Türkiye*” (A. Tirgil ve K. Altay ile), Sustainability, 2025, 17(21), 9840.",
        "“The Determinants of Greenhouse Gas Emissions Intensity in Global Value Chains” (A. Altun ve P. Tat ile), International Economic Journal, 2025, 39(2), 241-263.",
        "“The Role of Covid-19 Policy Responses on GVC Participation: The Turkish Experience” (A. Altun ve P. Tat ile), Journal of Economic Studies, 2025, 52(1), 104-118.",
        "“Do Turkish Firms Benefit from GVC Participation?*” (A. Altun ve T. Turan ile), International Journal of Emerging Markets, 2025, 20(2), 584-608.",
        "“Determinants of Labor Productivity of Turkish Manufacturing Sectors: The Role of Global Value Chain Participation” (A. Altun ve P. Tat ile), Journal of Productivity, 2024, 58(2), 155-170.",
        "“Do Lower Tariff Rates Promote Global Value Chain Participation?*” (A. Altun ve P. Tat ile), World Trade Review, 2024, 23(1), 1-19.",
        "“The Impacts of Openness and Global Value Chains on the Performance of Turkish Sectors*” (A. Altun ve P. Tat ile), Panoeconomicus, 2024, 71(2), 265-293.",
        "“The Changing Dynamics of Turkish Sectors within the Context of Trade in Emissions” (A. Altun ile), Journal of Sustainable Green Development, 2024, 1(1), 1-14.",
        "“International Trade Network and The Gravity Model” (H. Karaboğa ile), Journal of International Management Research and Applications, 2023, 2(2), 18-35.",
        "“The Early Impacts of Covid-19 on Production through Trade Shocks in Türkiye: An Analysis of International Production Chains” (A. Altun ve P. Tat ile), International Review of Economics and Management, 2023, 11(1), 17-34.",
        "“Compliance with IMF Conditions and Economic Growth*” (T. Turan ve A. Evrensel ile), Economic Change and Restructuring, 2023, 56(6), 4401–4420.",
        "“The Effects of Family Medicine System on the Households Health Expenditure in Turkey*” (A. Tirgil ve A. Altun ile), Journal of Public Health Policy, 2023, 44(1), 75-89.",
        "“An Empirical Analysis on the Impact of Investment Incentives to Regional Economic Growth in Turkey” (K. Altay ile), Economy of Regions, 2023, 19(3), 909-918.",
        "“Does GVC Participation Boost High Technology Exports?*” (A. Altun, I. Avşar, ve T. Turan ile), Journal of International Development, 2023, 35, 820-837.",
        "“Once Again ‘Smile Curve’: Is Chain Upgrading Possible?*” (A. Altun ve P. Tat ile), Review of Development Economics, 2023, 27(1), 62-88.",
        "“The Effect of Educational Mismatch on The Turkish Manufacturing Industry” (P. Tat ile), International Journal of Education Economics and Development, 2023, 14(4), 413-436.",
        "“The Power of Financial Incentives versus the Power of Suggestion*” (Z. Aktaş-Koral ve H. Çitçi ile), Sustainability, 2023, 15(4), 3652.",
        "“Does the Complexity of GVC Participation Matter for Productivity and Output Growth?*” (A. Altun ve P. Tat ile), European Journal of Development Research, 2022, 34(4), 2038-2068.",
        "“Economic Growth Effects of Public and Private Investment: Evidence from Dynamic Panel Estimation for Developed and Developing Countries*” (T. Turan ve H. A. Özer ile), Prague Economic Papers, 2021, 30(5), 613-631.",
        "“Beyond Conventional Trade: Trade Openness Implications of Trade in Value Added*” (A. Altun ile), Singapore Economic Review, 2021, 66(4), 973-995.",
        "“Implications of Participation in Global Value Chains for International Trade Network*” (H. Karaboğa ve A. Altun ile), Applied Economic Letters, Ağustos 2021, 28(14), 1169-1173.",
        "“External Debt, Growth and Investment for Developing Countries: Some Evidence for the Debt Overhang Hypothesis*” (T. Turan ile), Portuguese Economic Journal, 2021, 20(3), 319-341.",
        "“Does Capital Drain Reduce Total Factor Productivity in Developing Countries*” (A. Altun ile), Argumenta Oeconomia, 2020, (45)2, 53-75.",
        "“South-South Trade and North-South TRade for Growth and Productivity: A Cross-Country Analysis for the CIS Countries” (A. Altun ile), Hacettepe İİBF Dergisi, 2020, 38(2), 387-410.",
        "“The Impact of Global Value Chain Participation on Sectoral Growth and Productivity*” (A. Altun ile), Sustainability, 2020(12), 4848.",
        "“Natural Resource Rents and Capital Accumulation Nexus: Do Resource Rents Raise Public Human and Physical Capital Expenditures? (T. Turan ile), Environmental Economics and Policy Studies, 2020(22), 449-466.",
        "“Tax Structure and Economic Growth: Do Difference in Income Level and Government Effectiveness Matter?*” (T. Turan ile), Signapure Economic Review, 2020, 65(1), 217-237.",
        "“Openness and Deindustrialization: A Turkish Case” (A. Altun ve P. Tat ile), Boğaziçi Journal, Review of Social Economic and Administrative Studies, 2019, 33(2), 1-25.",
        "“Polity Stability, Economic Growth, and Investment: A Dynamic Panel Analysis” (T. Turan ile), Peace Economics, Peace Science and Public Policy, 2019, 25(1),1-21.",
        "“Impacts of Participation in Export Value Chains on TFP Growth” (A. Altun ile), Ege Akademik Bakış, 2019(1), 119-129.",
        "“Curse or Blessing? An Empirical Re-examination of Natural Resource-Growth Nexus*” (T. Turan ile), The Journal of International Development, 2018, 30(8), 1455-1473.",
        "“Assessing the Determinants of Customs-Related Transaction Costs in Turkey” (Z. Aktaş-Koral ile), Global Trade and Customs Journal, 13(10), 2018, 442-452.",
        "“Profitability Comparison of Conventional Banks and Islamic Banks: A Dynamic Panel Data Approach*” (N. Gümüş ve U. Y. Pabuççu ile) Pacific-Basin Finance Journal, 2018, 48, 99-111.",
        "“The Effectiveness of Investment Incentives in the Turkish Manufacturing Industry*” (H. Karaboğa ile), Prague Economic Papers, 2017, 26(6). 744-760.",
        "“Revisiting the Determinants of Long Run Growth: Do Different Measures of Growth Rates Matter?\" (A. Altun ile), The Empirical Economics Letters, 2017, 16(6), 591-596.",
        "“Causes and solutions for the stagnation of Islamic Banking in Turkey” (Y. U. Pabuççu ile), ISRA International Journal of Islamic Finance, 2017, 9(1), 43-61.",
        "“The Determinants of FDI in Transition Economies: A panel Data Analysis” (C. Gerni, M. K. Değer, O. S. Emsen, B. Kabadayı ile), Bandırma İİBF Yönetim ve Ekonomi Araştırmaları Dergisi, 2015 Eylül, 13(3), 101-120.",
        "“Petrol Fiyatlarının Enflasyona Geçişkenliği Değişti Mi?” (H. Kaya, D. Akgül ile), Central Bank Review, 2015, 15(3), 75-88.",
        "“Tax Smoothing Hypothesis: A Turkish Case*” (T. Turan ve M. Karakaş ile), Panoeconomicus, 2014(4), 487-501.",
        "“A Brief Analysis of the Tax Smoothing Hypothesis in Turkey*” (M. Karakaş ve T. Turan ile), The Transylvanian Review of Administrative Sciences, 2014(42), 78-93.",
        "“Impacts of Agricultural Supports on Exports of Individual Agricultural Products in Turkey” (Z. Aktaş-Koral ile), International Review of Economics and Management, 2013, 1(1), 1-37.",
        "“Effects of real exchange rates and their volatilities on selected Turkish agricultural commodities*” (H. Kaya and M. Koçtürk ile), Agricultural Economics, 2013, 59(5), 235–245.",
        "“Is Trade Liberalization a Solution to the Unemployment Problem*”, Portuguese Economic Journal, 2013, 12(1), 57-85.",
        "“Institutions and the Impact of Government Spending on Growth*” (J. L. Butkiewicz ile), Journal of Applied Economics, 2011, 14(2), 319-341.",
        "“Minerals, Openness, Institutions and Growth: An Empirical Analysis*” (J. L. Butkiewicz ile), Land Economics, 2010, 86(2), 313-328.",
        "“The Determinants of Infant Mortality in Turkey: A Disaggregated Analysis*” (S. Selim ile), İktisat İsletme ve Finans, Bilgesel Yayıncılık, 2010, 25 (286), 61-88.",
        "“Capital Account Openness, International Trade, and Economic Growth: A Cross-Country Empirical Investigation*” (J. L. Butkiewicz ile), Emerging Markets Finance and Trade, 2008, 44(2),15-38.",
        "“Time-Consistent Polities and Growth in Developing Countries: An Empirical Analysis*” (J. L. Butkiewicz ile), Review of World Economics, 2007, 143(2), 306-323.",
        "“Türkiye’de Vergi Ahlakını Belirleyen Faktörler Üzerine Bir Araştırma” (A. R. Gökbunar ve S. Selim ile), Ekonomik Yaklaşım Dergisi, 2007, 18(63), 69-94.",
        "“Institutional Quality and Economic Growth: Maintenance of the Rule of Law or Democratic Institutions, or Both?*” (J. L. Butkiewicz ile), Economic Modeling, 2006, 23(4), 648-661.",
        "“The Impact of Sociopolitical Instability on Economic Growth: Analysis and Implications*” (J. L. Butkiewicz ile), Journal of Policy Modeling, 2005, 27(5), 629-645.",
        "“The Effects of IMF and World Bank Lending on Long-Run Economic Growth: An Empirical Analysis*” (J. L. Butkiewicz ile), World Development, 2005, 33(3), 371-391.",
        "“Savunma Harcamalarını Belirleyen Faktörler ve Ekonomik Büyümeye Etkileri” (R. Gökbunar ile), Ankara Üniversitesi SBF Dergisi, 2004, 59(1), 159-179.",
        "“The Effect of International Financial Intervention on Economic Growth: A Review of the Evidence” (R. Gökbunar ile), Hacettepe Üniversitesi İİBF Dergisi, 2004, 22(1), 77-101.",
        "“Import Demand for the United States: A Translog Cost Function Analysis”, Akdeniz Üniversitesi İİBF Dergisi, 2004, 4(7), 145-155.",
        "“Türkiye’de Sürdürülebilir Ekonomik Büyüme: Her Zamankinden Daha Önemli” (R.Gökbunar ile) Active Bankacılık ve Finans Dergisi, Kasım-Aralık 2004, 7(39), 12-26.",
        "“Trade Openness and Economic Growth: A Cross-Country Empirical Investigation*”, Journal of Development Economics, 2003, 72(1), 57-89.",
        "“Household Consumption Expenditures in Peru: A Test for the Permanent Income Hypothesis”, Atatürk Üniversitesi İİBF Dergisi, 2003, 17(1-2), 65-73.",
        "“Do Trade Restrictions Hurt Economic Growth in Countries?”, Marmara Üniversitesi İİBF Dergisi, 2002, 17(1), 253-282.",
        "“Beşeri Sermaye Birikiminin Ekonomik Büyüme Sürecindeki Rolü Üzerine Ampirik Bir Çalışma”, İstatistik Araştırma Dergisi, 2002, 1(2), 287-306.",
        "“Testing the Factor Price Equalization Theorem in the Sixteen European Countries”, Erciyes Üniversitesi İİBF Dergisi, 2002, 18, 87-95.",
        "“Long-Term Capital Flows and Their Effects on Economic Growth through International Trade”, Boğaziçi Üniversitesi, Boğaziçi Journal, Review of Social Economic and Administrative Studies, 2001, 15(2), 109-128.",
        "“The Influence of Real Exchange Rates on Turkish Agricultural Exports”, Gazi Üniversitesi İİBF Dergisi, 2001, 69-80.",
        "“Does Capital Account Liberalization Raise Long-Run Economic Growth?”, Dokuz Eylül Üniversitesi İİBF Dergisi, 2001, 16(2), 133-148.",
        "“Convergence: A Cross Country Empirical Analysis”, Celal Bayar Üniversitesi Yönetim ve Ekonomi Dergisi, 2001, 7(1), 139-161."
      ]
    },
    {
      "category": "Yayımlanmış Kitaplar",
      "items": [
        "Trade Openness, Financial Openness, and Economic Growth, Lambert Academic Publishing, Saarbrücken, 2009.",
        "Avrupa Birliği Yolunda Esnaf ve Sanatkârlar (A. K. Çelebi, R. Gökbunar, A. A. Gülova ile), Ajansrenk, MESOB Yayınları: 3, Manisa, 2009.",
        "Avrupa Birliği’nin Türkiye’li Geleceği: Umutlar ve Korkular (R. Gökbunar ve S. Cura ile), Nobel Yayın Evi, Ankara, Mart 2008.",
        "Etkin Devlet ve Ekonomik Gelişme (R. Gökbunar ile), Odak Yayın Evi, Ankara, 2004."
      ]
    },
    {
      "category": "Kitapta Bölümler",
      "items": [
        "“Microfinance and Poverty Reduction in Somaliland” (A. M. Hussein ile), Yeni Ekonomik Trendler ve İş Fırsatları, (der. M. Yüce, M. Miynat, A. V. Can ve Ş. Sakarya), (pp. 53-62), Ekin Basın Yayın Dağıtım, Bursa, 2019.",
        "“Foreign Direct Investment and Greenhouse Gas Emissions: A Study on Developed and Developing Countries” (A. Altun ve P. Tat ile), in Sustainable Economy and Finance in the Age of Global Transformation: Governance, Policies, and Technologies, (der. Doç. Dr. C. Korkut ve Prof. Dr. M. Bulut), (pp. 291-312), TÜBA (Türkiye Bilimler Akademisi), Ankara, 2025.",
        "“Can Global Value Chain Participation Mitigate Conflict Between Nations in the Global Transformation Age?” (P. Tat ile), in Global Transformations and Türkiye, (der. Prof. Dr. Ahmet Nuri Yurdusev ve Dr. Öğr. Üyesi Mürsel Doğrul), (pp. 601-618), TÜBA (Türkiye Bilimler Akademisi), Ankara, 2024.",
        "“The Role of Voluntary Organizations in Building Trust” (G. G. Sağlam ile), Sustainability Practices - Cases from Business and Charities, (der. M. Bulut, C. Korkut ve M. T. Akpınar), (pp. 6-23), TÜBA (Turkish Academy of Sciences), Ankara, 2023.",
        "“Küresel Değer Zincirlerinin Bugünü ve Yarını Açısından Yapay Zekâ” (A. Altun ve Ö. Sebetçi ile), Yönetim Biliminde Yapay Zekâ, (der. S. Z. İmamoğlu, S. Erat ve H. İnce), (pp. 47-64), Nobel Bilimsel Eserler, Ankara, Ekim 2023.",
        "“Is the Global Economy on the Verge of Re-Globalization?” (A. Altun ile), International Trade: Past, Present and Future, (der. M. N. Rahman), (pp.1-18), Nova Science Publishers, 2023.",
        "“Kamu Harcamalarının Özel Yatırımlar Üzerinde Dışlama Etkisi: Mit mi Gerçek mi?” (T. Turan ile), in Kamu Mali Politikaları Üzerine Ekonometrik Analizler - Stata Uygulamalı (pp. 35-60), DER Yayınevi, Ankara, Nisan 2022.",
        "“Türkiye Ekonomisine Genel Bir Bakış” in Türkiye’nin Toplumsal Yapısı, (ed. H. Yazıcı), (pp. 253-301), Nobel Akademik Yayıncılık, Ankara, Ekim 2022.",
        "“The Role of Global Value Chains in Circular Economy” (A. Altun ve P. Tat ile), Circular Economy and Sustainable Living, (ed. M. Bulut and C. Korkut), (pp. 45-100), TÜBA (Turkish Academy of Sciences), Ankara, 2022.",
        "“Türkiye'de Orman Yangınlarının Turizm Üzerindeki Etkileri” (E. Kaymak ile), TÜBA (Türkiye Bilimler Akademisi), Orman Yangınları: Sebepleri, Etkileri, İzlenmesi, Alınması Gereken Önlemler ve Rehabilitasyon Faaliyetleri, (ed. T. Kavzoğlu), (pp. 319-340), TÜBA (Turkish Academy of Science), Ankara, 2021.",
        "“Covid-19 Salgını Sürecinde Tarım Sektörü: Girdi-Çıktı Tabloları Üzerinden Bir Değerlendirme” (A. Altun ile), Covid-19 Ekseninde Ekonomik ve Sosyal Dönüşüm, (der. A. Erdal ve S. Takmaz), (pp. 241-282). Nobel Akademik Yayıncılık, Ankara, 2020.",
        "“Mikrofinance and Poverty Reduction in Somaliland” (A. M. Hussein ile), Yeni Ekonomik Trendler ve İş Fırsatları, (der. M. Yüce, M. Miynat, A. V. Can ve Ş. Sakarya), (pp. 53-62), Ekin Basın Yayın Dağıtım, Bursa, 2019.",
        "“Küresel Değer Zincirlerinde Türkiye’nin Değişen Pozisyonu” (A. Altun ile), Uluslararası Ticaret: Değer Zinciri, Pazar Yapıları ve Muhasebe Uygulamaları, (der. A. Kara ve R. Sayar), (pp. 1-33), Ekin Basın Yayın Dağıtım, Bursa, 2019.",
        "“Competition in the Global Economy and Cultural Value Chains” (A. Altun ile), Political Economy: Institutions in a Global Economy, (der. M. Peter van der Hoek), (pp. 59-81). Forum for Economists International, Papendrecht, Netherlands, 2017.",
        "“Do Agricultural Support Payments Raise Olive Oil Exports in Turkey?” (Z. Aktaş-Koral ile), Economic Issues: Crises, Finance, and Agriculture, (der. S, Koç, A. Anlar ve E. Öruç), (pp. 170-194). IJOPEC Publication, Londra, 2017.",
        "“Tax Structure and Economic Growth: A GMM Analysis” (T. Turan ile), Social and Economic Dynamics of Development: Case Studies, (der. Savaş Çevik, Hamza Şimşek ve Harini Mitta), (pp. 107-114), IJOPEC Publication, Londra/İstanbul, 2016.",
        "“Terörizmin Ekonomik Kalkınmaya Etkisi”, Terör Ekonomisi, (der. A. R. Gökbunar, R. Gökbunar), (pp. 117-148), Beta Basım Yayım, İstanbul, Nisan 2010.",
        "“Küresel Ekonomide Küçük İşletmelerin Yeri ve Önemi”,    Kent Esnaf ve Zanaatkârlarının Sorunları ve Çözüm Önerileri, (der. Kent Araştırma Merkezi), (pp. 73-96), İstanbul, Mayıs 2008.",
        "“Kurumsal Faktörlerin Ekonomik Büyümeye Etkileri” (H. Karakayalı ile), Kurumsal İktisat, (der. C. C. Aktan), (pp. 135-157), SPK Kurumsal Araştırmalar Serisi, No: 2, Yayın: 194, Nisan 2006."
      ]
    },
    {
      "category": "Monografiler",
      "items": [
        "“Trade Liberalization, Output Growth and Employment Growth: A Cross-Country Empirical Investigation”, The Intergovernmental Group on Monetary Affairs and Development (G-24), 2005, 54 sayfa."
      ]
    },
    {
      "category": "Diğer Yayınlar",
      "items": [
        "“2018 Yılında Türk Ekonomisi Ne Olacak?”, Bilimevi İktisat, 2018.",
        "“15 Temmuz ve Devleti Yeniden İnşa Süreci”, 15 Temmuz Diriliş Destanı, (der. H. Okur), Semerkand Yayınları, İstanbul 2017, 68-71.",
        "“15 Temmuz Darbe Teşebbüsü Sonrasında Türkiye Ekonomisi”, Tümsiad Ekonomi, Temmuz-Ağustos 2017, 52.",
        "“On the Geographical Determinants of Bilateral Trade: ANFIS Approach” (M. H. Saka ve H. Karaboğa ile), değerlendirilme aşamasında.",
        "“Are SMEs Really More Productive with Fewer Jobs?” (A. Altun ve T. Turan ile), değerlendirilme aşamasında.",
        "“The Impacts of Matching Contributions on Retirement Savings: Evidence from a Quasi-Natural Experiment in Turkey” (S. H. Çitçi ile), değerlendirilme aşamasında.",
        "“Matching Contribution and Temptation: Evidence from Turkey” (S. H. Çitçi ile), değerlendirilme aşamasında.",
        "“Compliance with IMF Conditions and Investment” (T. Turan ve A. Evrensel ile), değerlendirilme aşamasında.",
        "“Compliance with IMF Conditions and Government Education Spending” (T. Turan ve A. Evrensel ile), değerlendirilme aşamasında.",
        "“The Impact of Hosting Syrian Refugees on Turkish Households’ Medical Expenditures” (A. Tirgil ve Z. B. Uğur ile), değerlendirilme aşamasında.",
        "“The Past and the Future Trade Patterns of the MENA Region: The Pursuit of Growth” (A. Altun ve P. Tat ile), değerlendirilme aşamasında.",
        "“Social Capital and Immigration: How Does Cultural Diversity Affect Outcomes?” (G. Sağlam ile), değerlendirilme aşamasında.",
        "“Role of Inter- and Intra-Industry GVC Participation in Sectoral Growth” (A. Altun ve P. Tat ile), değerlendirilme aşamasında.",
        "“The MENA Trade and Regional Conflicts: Causal Evidence from a Disaggregated Analysis” (P. Tat ile), değerlendirilme aşamasında.",
        "“How Does Foreign Direct Investment Affect Emission Intensity Embedded in Trade?” (A. Altun ve P. Tat ile), değerlendirilme aşamasında.",
        "“Foreign Direct Investment and Greenhouse Gas Emissions: A Study on Developed and Developing Countries” (A. Altun ve P. Tat ile), değerlendirilme aşamasında.",
        "“The Missing Link: Recognizing the Role of FDI-Related GVC Participation in Economic Growth” (A. Altun ve P. Tat ile), değerlendirilme aşamasında."
      ]
    },
    {
      "category": "Projeler",
      "items": [
        "“ReProCity: Rethinking Procurement in Cities: Circular and Socially Just Procurement for Urban Transformation”, Driving Urban Transitions (DUT) Partnership 2025, Circular Urban Economies (CUE) – Topic 3, Araştırmacı, Ocak 2027–Aralık 2029. Proje Özeti: Projede, kamu alımlarının döngüsel, doğa-pozitif ve sosyal açıdan adil kentsel dönüşüm için stratejik bir araç olarak kullanılması amaçlanmaktadır. Karlstad (İsveç), Kocaeli (Türkiye) ve Timișoara (Romanya)’da yürütülecek Urban Living Lab uygulamaları aracılığıyla, çevresel ve sosyal kriterleri kamu alım süreçlerine entegre eden SymbioCity Procurement Model geliştirilecek ve test edilecektir. Proje kapsamında ülkeler arası kamu alım mevzuatlarının ve uygulamalarının karşılaştırılması, ortak gösterge ve değerlendirme çerçevesinin geliştirilmesi ve döngüsellik, sosyal değer, biyoçeşitlilik ve yaşam döngüsü maliyetlerini içeren satın alma kriterlerinin oluşturulmasına katkı sağlanacaktır. Toplam 882.789,50 Euro bütçeye sahip olan proje, İsveç, Türkiye ve Romanya’dan 9 ortaklı uluslararası bir konsorsiyum tarafından yürütülmektedir.",
        "“CLIMACARE: Climate-Resilient Adaptive Environments for Urban Health and Social Equity”, Horizon Europe Innovation Action (HORIZON-MISS-2025-01-CLIMA-04), Koordinatör, Mayıs 2026–Mayıs 2030. Proje Özeti: Avrupa Birliği İklim Değişikliğine Uyum Misyonu (EU Mission on Adaptation to Climate Change) kapsamında desteklenen projede, aşırı sıcaklık risklerine karşı sağlık odaklı ve sosyal açıdan adil iklim uyum çözümlerinin geliştirilmesine katkı sağlanmıştır. Proje, demonstrasyon şehirlerinde uygulanacak müdahalelerin sağlık, sosyal eşitsizlik ve davranışsal etkilerini değerlendirmek üzere disiplinlerarası ve kanıta dayalı bir yaklaşım benimsemektedir. 10 milyon Euro bütçeye sahip olan proje, 10 ülkeden 28 ortaklı uluslararası bir konsorsiyum tarafından yürütülmektedir.",
        "“SBB-TÜBA Tematik Araştırmaları: Yapay Zekâ Teknolojilerinin Sosyal ve Kültürel Etkileri”, Türkiye Bilimler Akademisi (TÜBA) ve Cumhurbaşkanlığı, Strateji Bütçe Başkanlığı (SBB), Koordinatör, Ağustos 2025 – Haziran 2026.",
        "“Çevre Politikaları Bağlamında Doğrudan Yabancı Yatırımların Emisyonlar Üzerindeki Etkisi: Küresel Değere Zincirleri Çerçevesinde Bir Analiz”, Yürütücü, Araştırma Üniversite Destek Programı, Proje No: 2024-A-113-17, Haziran 2024 - Haziran 2026.",
        "“Sosyal ve Kültürel Alanda Türkiye’de Araştırma Potansiyeli ve Karşılaşılan Sorunlar ile Çözüm Önerileri”, Türkiye Bilimler Akademisi (TÜBA) ve Cumhurbaşkanlığı, Strateji Bütçe Başkanlığı (SBB), Koordinatör, Nisan 2024 - Aralık 2024.",
        "“Kişisel Deneyimler ve Bireysel Emeklilik Tasarrufları”, Yürütücü, Türkiye Bilimsel ve Teknolojik Araştırma Kurumu (TÜBİTAK) 1001, Proje No: 222K023, Mayıs 2023 - Kasım 2024.",
        "“Doğal Kaynaklar, Küresel Değer Zincirleri ve Sektörel Büyüme: EORA Veri Tabanından Kanıtlar”, Araştırmacı, Gebze Teknik Üniversitesi, Bilimsel Araştırma Projesi, Proje No: 2023-A-102-12, Temmuz 2023 - Temmuz 2024.",
        "“Küresel Değer Zincirlerine Sektörel Katılım ve İnovasyon Sisteminin Sektörel Performansı”, Araştırmacı, Gebze Ticaret Odası, 2021-2022.",
        "“Çayırova İlçesinde Kentsel Yaşam Kalitesini ve Kent Cazibesini Artırmaya Yönelik Stratejik Yol Haritası Hazırlanması”, Danışman, Gebze Teknik Üniversitesi, Teknoloji Transfer Ofisi Projesi, 2021-2022.",
        "“Türkiye’de Bireysel Emeklilik Politikalarının Sistemdeki Katılımcı Sayılarına ve Katkı Miktarlarına Etkisi”, Yürütücü, Gebze Teknik Üniversitesi, Bilimsel Araştırma Projesi, Proje No: 2021-A-102-12, Temmuz 2021 - Temmuz 2022.",
        "“Üretim ve Küresel Değer Zinciri Uzunluklarının Endüstrilerin Sektörel Performansı Üzerindeki Etkileri”, Yürütücü, Gebze Teknik Üniversitesi, Bilimsel Araştırma Projesi, Proje No: 2020-A-102-22, Eylül 2020 - Eylül 2021.",
        "“Tarihi Merkezlerde Yaratıcılık ve Girişimciliğin Gelişimi için İş İntübatörleri-LEARNING”, Danışman, İBB İnsan Kaynakları ve Eğitim Daire Başkanlığı, Aralık 2008 - Aralık 2009."
      ]
    },
    {
      "category": "Kongre/Sempozyumlar",
      "items": [
        "“Economic and Social Dimensions of Artificial Intelligence Technologies”, Summer School on Artificial Intelligence & Energy, 23 – 30 August 2026, Konya, Türkiye (Özet bildiri).",
        "“Osmanlı’dan Günümüze Kurumsal Değişim Sürecinde Ahlaki Çözülmenin Nedenleri Üzerine”, İstanbul İktisat Kongresi, TASAM, 9-10 Aralık, 2021, İstanbul, Türkiye.",
        "“Türkiye’de Uygulanan Yatırım Teşvik Politikalarının Bölgesel Ekonomik Büyümeye Etkisi: Düzey 3 Bölgeleri Bazında Ampirik Bir Analiz”, 6th Yıldız International Social Sciences Congress, 12-13 Aralık 2019, Istanbul, Türkiye.",
        "“Dynamic World Trade Network”, 12th International Days of Statistics and Economics, 6-8 Eylül 2018, Prag, Çek Cumhuriyeti (Tam metin bildiri).",
        "“Main Determinants of International Bilateral Trade - ANFIS Approach”, 3rd International Strategic Research Congress, 3-5 Mayıs 2018, Çorum, Turkey.",
        "“Do Automatic Enrollment Schemes Cannibalize Voluntary Retirement Saving? Evidence from a Nationwide Quasi-Experiment”, Economic Research Forum, 32ndAnnual Conference, 14-16 Haziran 2025, Kahire, Mısır (Tam metin bildiri).",
        "“Does Global Value Chain Participation Depress Labor Shares in Manufacturing?”, Economic Research Forum, 32ndAnnual Conference, 14-16 Haziran 2025, Kahire, Mısır (Tam metin bildiri).",
        "“How Does Foreign Direct Investment Affect Emission Intensity Embedded in Trade?”, International Balkans Cooperation Congress, 13-15 Mayıs 2026, İstanbul, Türkiye (Tam Metin Bildiri).",
        "“From Automation Threat to Deep Complementarity: The Polarization of AI Usage in Occupations in Türkiye”, International Symposium on Artificial Intelligence in Higher Education, 11-12 Mayıs 2026, Ankara, Türkiye (Davetli Konuşmacı, Tam Metin Bildiri).",
        "“Do Automatic Enrollment Schemes Cannibalize Voluntary Retirement Saving? Evidence from a Nationwide Quasi-Experiment”, Türkiye Ekonomi Kurumu Bahar Toplantısı (SMTEA2026), 7-9 Mayıs 2026, İstanbul, Türkiye.",
        "“Do Labor Shares Boost Forward GVC Participation in Manufacturing?”, 21stInternational Conference of MEEA, 29-30 Kasım 2025, İstanbul, Türkiye (Tam Metin Bildiri).",
        "“Carbon Emissions and Global Value Chains: Evidence from CBAM Sectors”, The 32ndConference on Economics - ICE-TEA2025, 13-15 Kasım 2025, Gazimağusa, Kuzey Kıbrıs Türk Cumhuriyeti.",
        "“The Missing Link: Recognizing the Role of FDI-Related GVC Participation in Economic Growth”, 8thInternational Conference on Entrepreneurship for Sustainability and Impact, 8-12 Kasım 2025, Doha, Katar (Tam Metin Bildiri).",
        "“Does Trade in Transportation Services Promote Manufacturing GVCs Participation?”, 20thAnnual Conference on Innovation and Competitiveness, 23-24 Ekim 2025, Varşova, Polonya (Tam Metin Bildiri).",
        "“Does GVC Participation Depress Labor Shares in Manufacturing?”, 7thBiannual International Scientific Conference Globalization and Regionalization in the Contemporary World, 26-27 Eylül 2025, Krakow, Polonya (Tam Metin Bildiri).",
        "“Does Participating in Agricultural Global Value Chains Promote Agricultural Growth?”, XVIII. EAAE Congress: Food System Transformation in Challenging Times, 26-29 Ağustos 2025, Bonn, Almanya (Tam Metin Bildiri).",
        "“Do Policy Incentives Foster Wise Financial Choices or Encourage Missteps?”, Türkiye Ekonomi Kurumu Bahar Toplantısı (SMTEA2025), 29-31 Mayıs 2025, İstanbul, Türkiye.",
        "“Do Savers Learn from Experience? Evidence from Pension Contributions”, Economic Research Forum, 31stAnnual Conference, 27-29 Nisan 2025, Kahire, Mısır (Tam metin bildiri).",
        "“Energy GVCs and Value-Added Growth: Evidence from EXIOBASE-3”, Economic Research Forum, 31stAnnual Conference, 27-29 Nisan 2025, Kahire, Mısır (Tam metin bildiri).",
        "“Impact of Foreign Direct Investment on Emission Intensity Embedded in Trade”, The 45thMEEA/ASSA Annual Conference, 7 Ocak 2025, San Francisco, ABD (Online).",
        "“Effects of Financial Intermediaries on Contribution Amount in Retirement Savings”, Ege 12thInternational Conference on Social Sciences, 26-30 Aralık 2024, İzmir, Türkiye.",
        "“Impact of Foreign Direct Investment on Emission Intensity Embedded in Trade”, International Association for Energy Economics, 3rdIAEE MENA Conference, 8-9 Aralık 2024, Riyad, Suudi Arabistan.",
        "“Impact of Foreign Direct Investment on Emission Intensity Embedded in Trade”, Turkish Science Academy (TÜBA), Sustainable Economy and the Future of Finance: Global Challenges and Opportunities Symposium, 29 Kasım 2024, Ankara, Türkiye.",
        "“Role of Inter- and Intra-Industry GVC Participation in Sectoral Growth”, Turkish Science Academy (TÜBA), Türkiye Economic Symposium, 7-8 Kasım 2024, Bursa, Türkiye.",
        "“Does Participating in Mining GVCs Lead to Lower Industrialization?”, International Conference on Eurasian Economies, 26-28 Haziran 2024, Bişkek, Kırgızistan (Tam metin bildiri).",
        "“The Impacts of Matching Contributions on Retirement Savings: Evidence from a Quasi-Natural Experiment”, Swiss Society of Economics and Statistics Annual Meeting, 6-7 Haziran 2024, Zürih, İsviçre.",
        "“Agricultural GVCs and Manufacturing Growth: Evidence from EXIOBASE-3 Database”, 5thInternational Conference on Economics, EconTR Conference, 16-18 Mayıs 2024, İstanbul, Türkiye.",
        "“The Impacts of Matching Contributions on Retirement Savings: Evidence from a Quasi-Natural Experiment”, Economic Research Forum, 30thAnnual Conference, 21-23 Nisan 2024, Rabat, Fas (En İyi Bildiri) (Tam metin bildiri).",
        "“The MENA Trade and Regional Conflicts: Causal Evidence from a Disaggregated Analysis”, Economic Research Forum, 30thAnnual Conference, 21-23 Nisan 2024, Rabat, Fas (Tam metin bildiri).",
        "“Does Global Value Chain Participation Lead to Economic Upgrading?”, Economic Research Forum, 30thAnnual Conference, 21-23 Nisan 2024, Rabat, Fas (Tam metin bildiri).",
        "“Can Global Value Chain Participation Mitigate Conflict Between Nations?”, Turkish Academy of Sciences (TÜBA), Conference on Global Transformations and Türkiye, 18-20 Nisan, 2024, İstanbul, Türkiye.",
        "“Does the FDI-Related GVC Differ from the Trade-Related GVC in Impact on Growth? The Role of Multinational Enterprises”, The 30thConference on Economics - ICE-TEA2023, 16-18 Kasım 2023, Antalya, Türkiye.",
        "“Reinforcement Learning in Individual Pension System: The Case of Turkiye”, 12thIstanbul Finance Congress, 21 Aralık 2023, İstanbul, Türkiye.",
        "“Does the FDI-Related GVC Differ from the Trade-Related GVC in Impact on Growth? The Role of Multinational Enterprises”, The 30thConference on Economics - ICE-TEA2023, 16-18 Kasım 2023, Antalya, Türkiye.",
        "“The Impact of Mineral Global Value Chains on Sectoral Value-Added Growth”, 3rdInternational Scientific Conference on Environmental Sustainability in Natural Resources Management, 20 Eylül 2023, Batum, Gürcistan (Tam metin bildiri).",
        "“Economic Growth Effects of IMF Programs”, International Conference on Eurasian Economies, 19-20 Eylül 2023, İzmir, Türkiye (Tam metin bildiri).",
        "“Yapısal Dış Ticaret Açığımız: Küresel Değer Zincirleri Bir Fırsat Penceresi Sunuyor mu?”, Türkiye İktisat Kongresi, 19-20 Temmuz 2023, İzmir, Türkiye (Davetli Konuşmacı).",
        "“Temptation and Saving Incentives”, IAREP-SABE 47thInternational Conference, 7-10 Haziran 2023, Nice, Fransa (Özet bildiri).",
        "“The Past and the Future Trade Patterns of the MENA Region: The Pursuit of Growth”, Economic Research Forum, 29thAnnual Conference 4-6 Mayıs 2023, Kahire, Mısır (Tam metin bildiri).",
        "“Yapısal Dış Ticaret Açığımız: Küresel Değer Zincirleri Bir Fırsat Penceresi Sunuyor mu?”, 100. Yılında İzmir İktisat Kongresi, 28-30 Nisan 2023, İzmir, Türkiye (Davetli Konuşmacı).",
        "“Do Lower Tariffs Promote Global Value Chain Participation?”, The 43rdMiddle East Economic Association (MEEA) / American Social Science Association (ASSA) Annual Meeting, 5-6 Ocak 2023, Beyrut, Lübnan (Tam metin bildiri).",
        "“Do Lower Tariffs Promote Global Value Chain Participation?”, The Conference of the Journal China and World Economy, 10 Aralık 2022, Pekin, Çin (Tam metin bildiri).",
        "“Are Tariffs Always Bad for Growth Evidence from Cross-Sectoral Analysis”, YouthEcon Graduate Seminar Program, 29 Ekim 2022.",
        "“The Role of Global Value Chains in Outsourcing Greenhouse Gas Emissions”, IRES, Louvain Institute of Data Analysis and Modeling in Economics and Statistics, Universitè Catholique de Louvain, IRES Afternoon, 6 Ekim 2022, Louvain-la-Neuve, Belçika.",
        "“The Productivity and Profitability Gains of the Top Turkish Industrial Enterprises from the Global Value Chains Participation”, International Conference on Eurasian Economies, 20-22 Eylül 2022, Bakü, Azerbaycan (En İyi Bildiri) (Tam metin bildiri).",
        "“Are Tariffs Always Bad for Growth? Evidence from Cross-Sectoral Analysis”, European Trade Study Group, 23rdAnnual Conference, 8-10 Eylül 2022, Groningen, Hollanda.",
        "“The Impacts of Matching Contributions on Retirement Savings: Evidence from a Quasi-Natural Experiment in Turkey”, 8thInternational Conference of Economics, ICE-TEA2022, 1-4 Eylül 2022, Nevşehir, Türkiye.",
        "“The Role of Voluntary Organizations in Building Trust”, TÜBA and AASSA Joint Symposium, 21-22 Mayıs 2022, ̇İstanbul, Türkiye (Tam metin bildiri).",
        "“The Role of Global Value Chains in Outsourcing Greenhouse Gas Emissions”, Economic Research Forum, 28thAnnual Conference, 26-30 Mart 2022, Giza, Mısır (En İyi Bildiri) (Tam metin bildiri).",
        "“Osmanlı'dan Günümüze Kruumsal Değişim Sürecinde Ahlaki Çözülmenin Nedenleri Üzerine”, İstanbul İktisat Kongresi, 9-10 Kasım, 2021, İstanbul, Türkiye.",
        "“The Role of Covid-19 Policy Responses on GVC Participation: The Turkish Experience”, Turkish Economic Association 21stNational Economics Symposium, 5-7 Kasım, 2021, Eskişehir, Türkiye.",
        "“The Impact of Global Value Chain Participation on Sectoral Growth and Productivity”, International Economic Association Online World Congress, 2-6 Temmuz 2021, Bali, Indonesia (Tam metin bildiri).",
        "“Is the Global Economy on the Verge of Re-globalizaiton?”, 2ndSANEM International Development Conference (SIDC), 17-19 Haziran 2021, Dhaka, Bangladesh (Tam metin bildiri).",
        "“The Impacts of COVID-19 on Production of Turkey: An Analysis of International Production Chains”, 7thInternational Conference of Economics, ICE-TEA2021, 9-11 Nisan 2021, Turkey.",
        "“Is Simple Participation Enough or Deeper Participation in GVCs Necessary? Evidence from 40 Major Economies”, 19thInternational Conference of MEEA, 9-11 Ekim 2020, İstanbul, Türkiye.",
        "“The Impacts of Production Lengths on Sectoral Perfromance: The Case of EU and US Industries”, International Conference ofn Economics, EconTR Conference, 10-12 Eylül 2020, Eskişehir, Türkiye.",
        "“The Effects of Openness and Global Value Chains on the Perfomance of Turkish Sectors”, Economic Research Forum, 26thAnnual Conference, 19 Ağustos 2020, Luksor, Mısır.",
        "“To Participate or not to Participate in GVCs: Evidence from the Production and GVCs Lenghts of EU and US Industries”, Warsaw International Economic Meeting, 15thAnnual Conference, 1-2 Temmuz 2020, Varşova, Polonya.",
        "“Türkiye’de Uygulanan Yatırım ve Teşvik Politikalarının Bölgesle Ekonomik Büyümeye Etkisi: Düzey 3 Bölgeleri Bazında Ampirik Bir Analiz”, 6thYıldız International Social Science Congress, 12-13 Aralık 2019, İstanbul, Türkiye.",
        "“Trade Openness and Deindustrialization: A Turkish Case”, 20thUlusal İktisat Sempozyumu, Türkiye Ekonomi Kurumu, 17-18 Ekim 2019, Adana, Türkiye.",
        "“Do Natural Resource Rents Raise Public Education Expenditures?”, 5thInternational El Ruha Conference on Social Science, 3-5 Ekim 2019, Tunus.",
        "“Trade Openness and Growth: New Evidence from Trade in Value Added Measures”, 8thInternational Conference ENTIME, 11-12 Nisan 2019, Gdansk, Polonya.",
        "“The Role of Microfinance on Welfare and Poverty Reduction in Somaliland”, 5thInternational Economics and Business Congress, 11-13 Nisan 2019, Bursa, Türkiye.",
        "“Impact of Foreign Direct Investment on Employment in Sudan“, 4thInternational Students Social Science Congress, 22-24 Kasım 2018, Nevşehir, Türkiye.",
        "“The Effect of Educational Mismatch on the Total Factor Productivity of Turkish Industry Sector”, Turkish Economic Association International Conference on Economics, 1-3 Kasım 2018, Antalya, Türkiye.",
        "“The Power of Financial Incentives versus the Power of Suggestion”, 13thNordic Conference in Behavioral and Experimental Economics, 28-29 September 2018, Odense, Danimarka.",
        "“Dynamics of World Trade Network”, 12thInternational Days of Statistics and Economics, 6-8 Eylül, 2018, Prag, Çek Cumhuriyeti",
        "“Does External Debt Matter for Investment: Evidence from GMM”, International Conference on Eurasian Economies, 18-20 Mayıs 2018, Taşkent, Özbekistan.",
        "“Türkiye’de Orta Gelir Tuzağı ve Kurumsal Değişim”, 3rdInternational Strategic Research Congress, 4 Mayıs 2018, Çorum, Türkiye (Davetli Konuşmacı).",
        "“Uluslararası İkili Ticaretin Temel Belirleyicileri – ANFIS Yaklaşımı”, 3rdInternational Strategic Research Congress, 3-5 Mayıs 2018, Çorum, Türkiye.",
        "“Is External Debt Harmful for Economic Growth?”, 2ndInternational Congress on Social Sciences, 23-25 March 2018, Al Quds, Filistin.",
        "“The Profitability of Banks in the OIC Member Countries”, International Islam and Economics Symposium, 10-11 March 2018, İstanbul, Türkiye (Davetli Konuşmacı).",
        "“Assessing the Determinants of Customs-Related Transaction Costs in Turkey”, 4thInternational Annual Meeting of Sosyoekonomi Society, 27-28 Ekim 2017, Viyana, Avusturya.",
        "“Does Participation in Global Value Chains Raise Total Factor Productivity Growth?”, International Strategic Research Congress, 28 Eylül-1 Ekim 2017, Antalya, Türkiye (Davetli Konuşmacı).",
        "“Curse or Blessing? A Re-Examination of Natural Resources-Growth Nexus”, International Social Sciences Congress, 18-24 Eylül 2017, Granada, İspanya.",
        "“The Relationship Between FDI and Total Factor Productivity Growth in Developing Countries”, 3rdInternational Congress on Economics and Business, 19-23 Mayıs 2017, Novi Sad, Sırbistan.",
        "“Impacts of Various Trade Flows on Growth and Productivity: A Cross-Country Analysis for CIS Countries”, Uluslararası Sosyal Bilimler Kongresi: Türkistan Forumu III, 26-28 Nisan 2017, Türkistan, Kazakistan.",
        "“Determination of the Factors Affecting Export Performance in Olive Oil Sector in Turkey”, European Congress for Economic Issues: Unregistered “Youth” Employment: Impacts, Policies, Remedies, and Local Practices, 30 Mart-1 Nisan 2017, Kocaeli, Türkiye.",
        "“Tax Structure and Economic Growth: A GMM Analysis”, 7thInternational Conference of Political Economy, 28-30 Haziran 2016, İstanbul, Türkiye.",
        "“Türk İmalat Sanayiinde Yatırım Teşviklerinin Etkinliği”, 2ndInternational Congress on Economıcs and Business, 30 Mayıs-3 Haziran 2016, Saraybosna, Bosna Hersek.",
        "“Polity Stability, Economic Growth, and Investment: A Dynamic Panel Analysis”, 2ndInternational Congress on Economıcs, Finance and Energy, 16-18 Mayıs 2016, Almati, Kazakistan.",
        "“Competition in the Global Economy and Cultural Value Chains”, 6thGlobal Conference, 18-21 Aralık 2015, Kuala Lumpur, Malezya.",
        "“Determinants of Bank Margin of Islamic and Interest Based Banks”, 2ndInternational Islamic Economics and Finance Conference, 11-13 Eylül 2015, İstanbul, Türkiye.",
        "“Institutions and the Impact of Government Spending on Growth”, Eastern Economic Association Annual Meeting, 27 Şubat-1 Mart 2009, New York, Amerika Birleşik Devletleri.",
        "“Minerals, Openness, Institutions and Growth: An Empirical Analysis”, Canadian Economic Association Annual Meeting at the University of British Columbia, 6-9 Haziran 2008, Vancouver, Kanada.",
        "“Time-Consistent Polities and Growth in Developing Countries: An Empirical Analysis”, TOBB Ekonomi ve Teknoloji Üniversitesi, Ekim 2006, Ankara, Türkiye.",
        "“Infant Mortality in Turkey: A Zero-Inflated Negative Binomial Application”, 2ndInternational Conference on Business, Economics, and Management, 15-18 Haziran 2006, Yaşar Üniversitesi, İzmir, Türkiye.",
        "“Political Instability and Economic Growth: A Cross-Country Empirical Investigation”, 6thMETU/ERC Conference on Economics, 11-14 Eylül 2002, Ankara, Türkiye.",
        "“Kurumsal Altyapının Ülkelerin Ekonomik Büyümelerine Etkisi”, Kocaeli Üniversitesi İktisadi ve İdari Bilimler Fakültesi, Bilgi ve Ekonomi Kongresi, 10-11 Mayıs 2002, Kocaeli, Türkiye.",
        "“Beşeri Sermaye Birikiminin Ekonomik Büyüme Sürecindeki Rolü Üzerine Ampirik Bir Çalışma”, T.C. Başbakanlık, Devlet İstatistik Enstitüsü, İstatistik Araştırma Sempozyumu, 12-14 Kasım 2001, Ankara, Türkiye."
      ]
    }
  ],
  "publications_footnote": "* Social Sciences Citation Index (SSCI)’de bulunmaktadır."
};